[phases.setup]
nixPkgs = ["ffmpeg", "libsodium", "libsodium-dev", "libffi", "pkg-config"]

[phases.build]
envs = { SODIUM_INSTALL = "system" }
cmds = ["pip install --upgrade pip", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn dashboard:app --host 0.0.0.0 --port $PORT"
